spring:
    application:
        name: sched_mgmt
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sched_mgmt
        username: postgres
        password: postgresql
    messages:
        basename: prop/messages,prop/validation_messages
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:/mapper/postgreSQL/*.xml
    type-aliases-package: d_tanabe.sched_mgmt.model
